# Problem Statement-Predicting if a customer will buy credit card  using Naive bayes

# step 1 -Import required libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [ ]:
cd C:\Mehul Session\Session 27_Python Introduction\LMS FT\LMS Python\1_Python_Session_File\5_Machine Learning\7_Naive_Bayes

# Step-2 Import dataset

In [10]:
df = pd.read_csv("Naïve Bayes Updated Resourses16963293170.csv")

# In realtime also you can get dataset without headers

In [11]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [13]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [10]:
df.describe()

Time             V1             V2             V3  \
count  232381.000000  232381.000000  232381.000000  232381.000000   
mean    80353.776006      -0.062359      -0.016408       0.163173   
std     40206.844649       1.954966       1.671755       1.498139   
min         0.000000     -56.407510     -72.715728     -33.680984   
25%     48231.000000      -0.946554      -0.603264      -0.603694   
50%     74177.000000      -0.026944       0.066069       0.353145   
75%    121850.000000       1.246247       0.780990       1.142350   
max    147147.000000       2.454930      22.057729       9.382558   

                  V4             V5             V6             V7  \
count  232381.000000  232381.000000  232381.000000  232381.000000   
mean        0.040472      -0.057423       0.027727      -0.023697   
std         1.413361       1.377227       1.324713       1.231100   
min        -5.683171     -42.147898     -26.160506     -43.557242   
25%        -0.827942      -0.743847      -0.735777      -0.567537   
50%         0.035503      -0.116068      -0.240866       0.012682   
75%         0.828097       0.540518       0.430953       0.536567   
max        16.875344      34.801666      22.529298      36.877368   

                  V8             V9  ...            V21            V22  \
count  232380.000000  232380.000000  ...  232380.000000  232380.000000   
mean        0.003138       0.002496  ...      -0.005344      -0.020154   
std         1.207694       1.121371  ...       0.743975       0.710735   
min       -73.216718     -13.434066  ...     -34.830382     -10.933144   
25%        -0.196894      -0.660050  ...      -0.225448      -0.533396   
50%         0.032369      -0.065525  ...      -0.033823      -0.009404   
75%         0.331737       0.611860  ...       0.170416       0.477427   
max        20.007208      15.594995  ...      27.202839      10.503090   

                 V23            V24            V25            V26  \
count  232380.000000  232380.000000  232380.000000  232380.000000   
mean       -0.009277       0.000613       0.034420       0.002835   
std         0.640584       0.606437       0.510248       0.486570   
min       -44.807735      -2.836627     -10.295397      -2.604551   
25%        -0.166716      -0.349544      -0.276733      -0.330885   
50%        -0.021936       0.047011       0.070619      -0.059624   
75%         0.128576       0.428331       0.371653       0.252166   
max        22.528412       4.022866       7.519589       3.517346   

                 V27            V28         Amount          Class  
count  232380.000000  232380.000000  232380.000000  232380.000000  
mean        0.000081       0.001740      91.087229       0.001816  
std         0.402849       0.334431     252.696281       0.042576  
min       -22.565679     -11.710896       0.000000       0.000000  
25%        -0.069872      -0.048546       6.000000       0.000000  
50%         0.003194       0.015495      23.450000       0.000000  
75%         0.089163       0.078056      79.990000       0.000000  
max        12.152401      33.847808   19656.530000       1.000000  

[8 rows x 31 columns]

In [14]:
df = df.drop(['Time'],axis=1)


# Data Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
df['scaled_Amount'] = StandardScaler().fit_transform(df['Amount'].values.reshape(-1,1))
df = df.drop(['Amount'],axis=1)

In [16]:
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Class  scaled_Amount  
0  0.128539 -0.189115  0.133558 -0.021053      0       0.244964  
1  0.167170  0.125895 -0.008983  0.014724      0      -0.342475  
2 -0.327642 -0.139097 -0.055353 -0.059752      0       1.160686  
3  0.647376 -0.221929  0.062723  0.061458      0       0.140534  
4 -0.206010  0.502292  0.219422  0.215153      0      -0.073403  

[5 rows x 30 columns]

# Model Intialization

In [17]:
X = df.drop(['Class'],axis = 1)
y =df.Class

# Training Dataset

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.2)

In [20]:
X_train.shape , y_train.shape

((227845, 29), (227845,))

In [21]:
from sklearn.naive_bayes import GaussianNB

In [22]:
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [23]:
model.score(X_train,y_train)


0.9780552568632184

In [24]:
model.score(X_test,y_test)


0.9787402127734279

In [25]:
model.predict(X_test[0:5])


array([0, 0, 0, 0, 0], dtype=int64)

In [26]:
y_test[:5]

207447    0
70094     0
70105     0
51114     0
134425    0
Name: Class, dtype: int64

In [27]:
model.predict_proba(X_test[:5])


array([[1.00000000e+00, 5.23759586e-14],
       [1.00000000e+00, 5.58887344e-17],
       [1.00000000e+00, 1.12315081e-16],
       [1.00000000e+00, 5.53273085e-16],
       [1.00000000e+00, 2.33341464e-14]])

In [28]:
y_pred = model.predict(X_test)

In [29]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [31]:
confusion_matrix(y_test,y_pred)

array([[55671,  1194],
       [   17,    80]], dtype=int64)

In [32]:
accuracy_score(y_test,y_pred)

0.9787402127734279

In [51]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99     56865
           1       0.06      0.82      0.12        97

    accuracy                           0.98     56962
   macro avg       0.53      0.90      0.55     56962
weighted avg       1.00      0.98      0.99     56962



In [35]:
from sklearn.ensemble import RandomForestClassifier


In [41]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [42]:
rfc.score(X_train,y_train)

1.0

In [43]:
rfc.score(X_test,y_test)

0.9995786664794073

In [44]:
y_pred1 = rfc.predict(X_test)

In [45]:
confusion_matrix(y_test,y_pred1)

array([[56862,     3],
       [   21,    76]], dtype=int64)

In [50]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56865
           1       0.96      0.78      0.86        97

    accuracy                           1.00     56962
   macro avg       0.98      0.89      0.93     56962
weighted avg       1.00      1.00      1.00     56962

