# NUMPY

NumPy is a Python library that is the core library for scientific computing in Python. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices. To work with these arrays, there’s a vast amount of high-level mathematical functions operate on these matric

#### Arrays can store data very compactly and are more efficient for storing large amounts of data. Arrays are great for numerical operations; lists cannot directly handle math operations

# Difference Btwn List and array

#### A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 

#### A list is the Python equivalent of an array, but is resizeable and can contain elements of different types.

# In List we can pass different datatypes but in array we can only give similar Datatypes

# Creating Array

In [1]:
import numpy as np

In [2]:
a=[1,2,4,6,8]

In [3]:
#with list
arr = np.array(a)

arr

array([1, 2, 4, 6, 8])

In [4]:
#check data type
type(arr)

numpy.ndarray

In [5]:
# with tuple
arr = np.array((1, 2, 3, 4, 5))

arr

array([1, 2, 3, 4, 5])

In [ ]:
#add list into np
lis=[1,2,4,6,8]

arr=np.array(lis)
arr

In [ ]:
arr


In [15]:
#Return a new array of given shape and type, with random values..


a = np.empty([5,5],  dtype = int) 
a

array([[1865722616,        480,         64,          0,          0],
       [         0,          0,          0,          0,  358220391],
       [ 945907297, 1698128437,  825831477, 1681024610,  811688248],
       [1700934192,  912614967,  925906485,  909325881, 1630548537],
       [ 862020193,  909194853,  892822630,  842478648,  912339253]])

In [18]:
#The numpy.ones() function returns a new array of given shape and type, with ones.
a = np.zeros([4,2], dtype=int) 
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
a = np.zeros((5,2), dtype = int) 
a

In [21]:
#create array with ones
a = np.ones([2,6], dtype=int) 
a

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:
range(1,10,2)

In [24]:
#create array with range
a = np.arange(2,10,2) 
a

array([2, 4, 6, 8])

 Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop,step)

In [29]:
#with condition 
a = np.arange(0,100,5) 
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.

In [28]:
#using line space, number of sample =5
a = np.linspace(0,100,5) 
a

array([  0.,  25.,  50.,  75., 100.])

# Dimension

In [30]:
#Zero dimension
arr = np.array(42)

print(arr)
 
print(arr.ndim)

42
0


In [31]:
#one dimension
arr = np.array([1, 2])

print(arr)

print(arr.ndim)

[1 2]
1


More than one dimension:

In [32]:
#Two dimension

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
#Three dimension

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

print(arr.ndim)

In [33]:
#multiple dimension
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print(arr.ndim)


[[[[[1 2 3 4]]]]]
5


In [39]:
#random method to creat array
a = np.random.rand(10)*100
a

array([ 6.57836379, 82.37748255, 12.60131855, 94.41509447, 17.75528384,
       78.77923981, 31.91891248, 24.00078662, 28.52344736, 24.69492643])

Random sampling in numpy | randint() function

In [43]:
a = np.random.randint(20, size=(10,5))

a

array([[ 9, 16, 10,  2, 10],
       [16, 11, 11, 14,  7],
       [16, 18,  5,  1,  9],
       [ 4, 14, 16, 19,  2],
       [ 6, 16,  6,  7,  6],
       [16,  0,  4,  5, 11],
       [ 9, 13,  1,  9, 18],
       [ 3,  7, 11, 17, 16],
       [12,  1, 14, 18, 12],
       [ 3, 16, 12, 11,  7]])

In [44]:
a = np.random.rand(4)

a

array([0.35163932, 0.94515344, 0.68001977, 0.87607293])

In [45]:
a = np.random.rand(2,2)

a


array([[0.85519987, 0.34778572],
       [0.55642448, 0.27363803]])

Return one of the values in an array:

In [52]:

a = np.random.choice(['H','T'])

a

'T'

Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)

In [54]:
a = np.random.choice([3, 5, 7, 9], size=(2, 3))

a

array([[5, 3, 9],
       [3, 5, 7]])

# Data type

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [55]:
#int
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [56]:
type(arr)

numpy.ndarray

In [59]:
#string
arr = np.array(['python123456', 'java', 'c'])

print(arr.dtype)

<U12


In [62]:
#convert data type
arr = np.array([12.3,16.64,21.34])

new_arr = arr.astype('i')


In [63]:
print(arr)
print(new_arr)
print(new_arr.dtype)

[12.3  16.64 21.34]
[12 16 21]
int32


In [67]:
arr = np.array([-4, 0.25, 2.5])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True  True  True]
bool


# COPY Array

In [68]:
arr = np.array([10,20,30,40,50])
a = arr.copy()

In [76]:
print(arr)
print(a)

[100  20  30  40  50]
[100  20  30  40  50]


In [70]:
arr[-1]=1

Make a view, change the original array, and display both arrays

In [71]:
print(arr)
print(a)

[10 20 30 40  1]
[10 20 30 40 50]


In [72]:
#view, changing in view array affect orignal arrray

arr = np.array([10,20,30,40,50])
a = arr.view()


In [73]:
print(arr)
print(a)

[10 20 30 40 50]
[10 20 30 40 50]


In [74]:
arr[0] = 100

In [75]:
print(arr)
print(a)

[100  20  30  40  50]
[100  20  30  40  50]


# Indexing & slicing

In [77]:
arr = np.array([10,20,30,40,50])

arr[0]

10

In [78]:

arr[1]

20

In [79]:

arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])
print(arr)


[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [80]:
arr[0, 1]

20

In [81]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [82]:
arr[0, -2]

4

In [83]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [84]:
arr[:2,:3]


array([[1, 2, 3],
       [2, 3, 4]])

In [85]:
arr[2:,3:]


array([[8, 9]])

In [86]:
arr[:,3:]


array([[4, 5],
       [5, 6],
       [8, 9]])

# Shape

In [98]:
arr = np.array([[1,2,3,4,5], [6,9,10]], ndmin=5)

print(arr)
print(".......................")

print(arr.shape)


[[[[[list([1, 2, 3, 4, 5]) list([6, 9, 10])]]]]]
.......................
(1, 1, 1, 1, 2)


C:\Users\trainer1\AppData\Local\Temp/ipykernel_6620/1807506173.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[1,2,3,4,5], [6,9,10]], ndmin=5)


In [99]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
arr.shape


[[[[[1 2 3 4]]]]]


(1, 1, 1, 1, 4)

# Reshape

In [107]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10])
print(arr)

print("-------------------------     ")

new_arr = arr.reshape(5,1,2)

print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]
-------------------------     
[[[ 1  2]]

 [[ 3  4]]

 [[ 5  6]]

 [[ 7  8]]

 [[ 9 10]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr)

newarr = arr.reshape(2, 2, 3)

print(newarr)

# iterating

In [108]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [109]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [110]:
for i in arr:
    print(i)

[1 2 3 4 5]
[2 3 4 5 6]
[9 7 6 8 9]


In [111]:
for i in np.nditer(arr):
     print(i)

1
2
3
4
5
2
3
4
5
6
9
7
6
8
9


# Transpose  array

rotate array 

In [ ]:
arr

In [112]:

print(arr)

print("__________")

Tran_arry  = arr.T 

print(Tran_arry)


[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
__________
[[1 2 9]
 [2 3 7]
 [3 4 6]
 [4 5 8]
 [5 6 9]]


# sorting 

In [113]:
arr = np.array([7,2,23,15,11])
print(arr)
print(np.sort(arr))

[ 7  2 23 15 11]
[ 2  7 11 15 23]


In [114]:
#two dim array sort
arr = np.array([[20,10], [3,7]])
print(arr)
print("-------------------")
new_arr = np.sort(arr)        
new_arr

[[20 10]
 [ 3  7]]
-------------------


array([[10, 20],
       [ 3,  7]])

In [115]:
#sorting by axis , row ,column
arr = np.array([[20,10], [3,7]])
print(arr)
print('--------------------------')
new_arr = np.sort(arr, axis = 0) 
new_arr

[[20 10]
 [ 3  7]]
--------------------------


array([[ 3,  7],
       [20, 10]])

# Searching

In [116]:
arr = np.array([2,2,5,7,8,2,5,9])

arr = np.where(arr == 2)

print(arr)

(array([0, 1, 5], dtype=int64),)


# Splitting 

In [120]:
arr = np.array([2,2,5,4,5,6,7,8,9,10])

newarr = np.array_split(arr, 4)

print(newarr)


[array([2, 2, 5]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]


# joining

In [121]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.concatenate((arr, arr1))

arr

array([ 2,  4,  6,  8, 10, 12])

In [122]:
arr = np.array([[2, 4], [6, 8]])

arr1 = np.array([[10, 12], [14, 16]])

arr = np.concatenate((arr, arr1), axis=0) 

arr

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [124]:
#try with 1
arr = np.array([[2, 4], [6, 8]])

arr1 = np.array([[10, 12], [14, 16]])

arr = np.concatenate((arr, arr1), axis=0)

arr

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [125]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.hstack((arr, arr1))

arr


array([ 2,  4,  6,  8, 10, 12])

In [126]:

arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.vstack((arr, arr1))

arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [127]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])


arr = np.dstack((arr, arr1))

arr

array([[[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

# String , arithmmetic , static opration

In [129]:
arr = np.array(['usa', 'india', 'russia'])

new_arr = np.char.lower(arr)

new_arr

array(['usa', 'india', 'russia'], dtype='<U6')

In [130]:
arr= np.char.join('|', 'FINGERTIPS')
arr

array('F|I|N|G|E|R|T|I|P|S', dtype='<U19')

In [132]:
arr = np.array([2.344,6.232,8.34,5,3.5,4.36]) 

#np.around(arr) 

In [133]:
np.around(arr, decimals = 1) 

array([2.3, 6.2, 8.3, 5. , 3.5, 4.4])

In [136]:
np.ceil(arr)

array([3., 7., 9., 5., 4., 5.])

In [137]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])


In [138]:
np.add(arr,arr1) 

array([10, 14, 18])

In [139]:
np.subtract(arr,arr1) 

array([-6, -6, -6])

In [140]:
np.multiply(arr,arr1) 

array([16, 40, 72])

In [141]:
np.divide(arr1,arr)

array([4. , 2.5, 2. ])

In [142]:
np.power(arr,2) 

array([ 4, 16, 36], dtype=int32)

In [143]:
np.mod(arr1,arr) 

array([0, 2, 0], dtype=int32)

In [144]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [145]:
np.median(arr) 

6.5

In [146]:
np.mean(arr) 

6.5

In [147]:
np.average(arr) 

6.5

In [148]:
np.std(arr)

3.452052529534663

In [149]:
np.var(arr)

11.916666666666666